import { ensureLaboratoryCatalog } from './laboratoryCatalog.js';
const CREATED_AT = '2026-01-01T00:00:00.000Z';

const cbcTests = [
  ['test-hgb', 'HGB', 'Hemoglobin', 'g/dL', 1],
  ['test-wbc', 'WBC', 'Total Leukocyte Count', '10^9/L', 2],
  ['test-neut', 'NEUT', 'Neutrophils', '%', 3],
  ['test-lym', 'LYM', 'Lymphocytes', '%', 4],
  ['test-eos', 'EOS', 'Eosinophils', '%', 5],
  ['test-mono', 'MONO', 'Monocytes', '%', 6],
  ['test-baso', 'BASO', 'Basophils', '%', 7],
  ['test-plt', 'PLT', 'Platelet Count', '10^9/L', 8],
  ['test-rbc', 'RBC', 'Total RBC Count', '10^12/L', 9],
  ['test-hct', 'HCT', 'Hematocrit', '%', 10],
  ['test-mcv', 'MCV', 'Mean Corpuscular Volume', 'fL', 11],
  ['test-mch', 'MCH', 'Mean Cell Hemoglobin', 'pg', 12],
  ['test-mchc', 'MCHC', 'Mean Cell Hemoglobin Concentration', '%', 13],
];

const ranges = {
  HGB: [13, 17, 7, 20],
  WBC: [4.8, 10.8, 2, 30],
  NEUT: [40, 80, 20, 90],
  LYM: [20, 40, 5, 70],
  EOS: [1, 6, 0, 20],
  MONO: [2, 10, 0, 25],
  BASO: [0, 2, 0, 10],
  PLT: [150, 410, 50, 1000],
  RBC: [4.5, 6, 2, 8],
  HCT: [40, 52, 20, 65],
  MCV: [80, 100, 60, 130],
  MCH: [27, 32, 15, 45],
  MCHC: [31.5, 34.5, 20, 45],
};

export function createInitialState() {
  const testCatalog = cbcTests.map(([testId, testCode, testName, defaultUnit, sortOrder]) => ({
    testId,
    testCode,
    testName,
    defaultUnit,
    sampleTypeId: 'sample-blood',
    methodology: 'Automated analyzer',
    sortOrder,
    isActive: true,
    createdAt: CREATED_AT,
  }));
  const panelTests = cbcTests.map(([testId, , , , sortOrder]) => ({
    panelTestId: `panel-cbc-${testId}`,
    panelId: 'panel-cbc',
    testId,
    sortOrder,
    isRequired: true,
  }));
  const referenceRanges = testCatalog.map((test) => {
    const [normalLow, normalHigh, criticalLow, criticalHigh] = ranges[test.testCode];
    return {
      rangeId: `range-${test.testCode.toLowerCase()}-adult-any`,
      testId: test.testId,
      sex: 'Any',
      ageMin: 18,
      ageMax: 120,
      ageUnit: 'years',
      normalLow,
      normalHigh,
      unit: test.defaultUnit,
      criticalLow,
      criticalHigh,
      interpretationNote: 'Interpret with clinical findings and laboratory policy.',
      isActive: true,
    };
  });

  const state = {
    schemaVersion: 1,
    revision: 0,
    facilities: [{
      facilityId: 'facility-rhu-main',
      facilityName: 'RHU Laboratory Department',
      facilityType: 'Rural Health Unit',
      address: 'Synthetic Phase One facility',
      contactNumber: null,
      email: 'laboratory@example.invalid',
      website: null,
      logoPath: null,
      createdAt: CREATED_AT,
      updatedAt: null,
    }],
    staffProfiles: [
      { staffId: 'staff-doctor-seed', authUserId: 'doctor-seed', staffCode: 'ST-DOC-001', firstName: 'Synthetic', middleName: null, lastName: 'Doctor', role: 'Doctor', licenseNumber: 'SYN-MD-001', isActive: true, createdAt: CREATED_AT },
      { staffId: 'staff-lab-seed', authUserId: 'lab-seed', staffCode: 'ST-LAB-001', firstName: 'Synthetic', middleName: null, lastName: 'Technologist', role: 'MedTech', licenseNumber: 'SYN-RMT-001', isActive: true, createdAt: CREATED_AT },
      { staffId: 'staff-supervisor-seed', authUserId: 'supervisor-seed', staffCode: 'ST-SUP-001', firstName: 'Synthetic', middleName: null, lastName: 'Supervisor', role: 'Pathologist', licenseNumber: 'SYN-PATH-001', isActive: true, createdAt: CREATED_AT },
    ],
    requestingPhysicians: [{ physicianId: 'physician-seed', authUserId: 'doctor-seed', fullName: 'Synthetic Doctor', licenseNumber: 'SYN-MD-001', specialization: 'General Medicine', clinicName: 'RHU Main Clinic', contactNumber: null }],
    sampleTypes: [{ sampleTypeId: 'sample-blood', sampleName: 'Blood', description: 'Venous blood sample', isActive: true }],
    testPanels: [{ panelId: 'panel-cbc', panelCode: 'CBC', panelName: 'Complete Blood Count', department: 'Haematology', description: 'CBC panel with differential count', isActive: true }],
    testCatalog,
    panelTests,
    referenceRanges,
    reportTemplates: [{ templateId: 'template-cbc', templateName: 'CBC Printout', panelId: 'panel-cbc', headerTitle: 'HAEMATOLOGY', sectionTitle: 'COMPLETE BLOOD COUNT (CBC)', footerNote: 'Generated by RHU Laboratory EHR System', medicoLegalNote: 'Not valid for medico legal purpose', isActive: true }],
    signatories: [],
    patients: [],
    patientAccountLinks: [],
    visits: [],
    consultations: [],
    labOrders: [],
    orderPanels: [],
    orderItems: [],
    payments: [],
    specimens: [],
    labReports: [],
    resultVersions: [],
    resultItems: [],
    resultInterpretations: [],
    testAttempts: [],
    qcChecks: [],
    repeatTests: [],
    referrals: [],
    releases: [],
    doctorReviews: [],
    emailLogs: [],
    printLogs: [],
    attachments: [],
    audits: [],
    statusHistory: [],
    outbox: [],
    publicationReceipts: [],
    syncOperations: [],
    syncReceipts: [],
    idempotencyRecords: [],
  };
  ensureLaboratoryCatalog(state);
  return state;
}
