export const ROLES = Object.freeze([
  'SYSTEM_ADMIN',
  'REGISTRATION_CASHIER',
  'DOCTOR',
  'LAB_STAFF',
  'LAB_SUPERVISOR',
  'PATIENT',
  'PUBLIC_VERIFIER',
]);

export const ORDER_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  PAYMENT_CLASSIFIED: 'PAYMENT_CLASSIFIED',
  ACCESSIONED: 'ACCESSIONED',
  COLLECTED: 'COLLECTED',
  IN_TESTING: 'IN_TESTING',
  FOR_VERIFICATION: 'FOR_VERIFICATION',
  APPROVED: 'APPROVED',
  STORAGE_PENDING: 'STORAGE_PENDING',
  STORED: 'STORED',
  LEDGER_PENDING: 'LEDGER_PENDING',
  LEDGER_REGISTERED: 'LEDGER_REGISTERED',
  RELEASED: 'RELEASED',
  RECOLLECTION_REQUIRED: 'RECOLLECTION_REQUIRED',
  CANCELLED: 'CANCELLED',
});

export const ORDER_DISPLAY_STATUS = Object.freeze({
  REQUESTED: 'Pending',
  PAYMENT_CLASSIFIED: 'Pending',
  ACCESSIONED: 'Pending',
  COLLECTED: 'Collected',
  IN_TESTING: 'Processing',
  FOR_VERIFICATION: 'Processing',
  APPROVED: 'Completed',
  STORAGE_PENDING: 'Completed',
  STORED: 'Completed',
  LEDGER_PENDING: 'Completed',
  LEDGER_REGISTERED: 'Completed',
  RELEASED: 'Released',
  RECOLLECTION_REQUIRED: 'Pending',
  CANCELLED: 'Cancelled',
});

export const RESULT_VERSION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  QC_PENDING: 'QC_PENDING',
  QC_PASSED: 'QC_PASSED',
  QC_FAILED: 'QC_FAILED',
  REPEAT_REQUIRED: 'REPEAT_REQUIRED',
  REFERRED: 'REFERRED',
  FOR_VERIFICATION: 'FOR_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  RELEASED: 'RELEASED',
  SUPERSEDED: 'SUPERSEDED',
  CANCELLED: 'CANCELLED',
});

export const RESULT_DISPLAY_STATUS = Object.freeze({
  DRAFT: 'Draft',
  QC_PENDING: 'Draft',
  QC_PASSED: 'Draft',
  QC_FAILED: 'Draft',
  REPEAT_REQUIRED: 'Draft',
  REFERRED: 'Draft',
  FOR_VERIFICATION: 'For Verification',
  VERIFIED: 'Verified',
  REJECTED: 'Draft',
  RELEASED: 'Released',
  SUPERSEDED: 'Cancelled',
  CANCELLED: 'Cancelled',
});

export const PAYMENT_CLASSIFICATIONS = Object.freeze(['Paid', 'Free', 'Waived', 'Subsidized']);
export const RESULT_FLAGS = Object.freeze(['Normal', 'Low', 'High', 'Critical Low', 'Critical High', 'Abnormal']);
export const SPECIMEN_STATUS = Object.freeze(['ACCESSIONED', 'COLLECTED', 'RECEIVED', 'REJECTED', 'IN_TESTING', 'PROCESSED', 'STORED']);
export const PUBLICATION_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  STORAGE_PENDING: 'STORAGE_PENDING',
  STORED: 'STORED',
  LEDGER_PENDING: 'LEDGER_PENDING',
  REGISTERED: 'REGISTERED',
  RELEASE_PENDING: 'RELEASE_PENDING',
  COMPLETE: 'COMPLETE',
  RETRY_WAIT: 'RETRY_WAIT',
  FAILED_REVIEW: 'FAILED_REVIEW',
});
